/* The following code was generated by JFlex 1.4.3 on 10/09/01 6:36 */

/*
»ú¶ç²òÀÏ(lexer.mll)
 
¥³¥ó¥Ô¥å¡¼¥¿¤Ë¤È¤Ã¤Æ¤Ï¡¢ML¥×¥úÁ°¥é¥à¤È¤¤¤¨¤É¤â¡¢¤Ï¤¸¤á¤Ï¤¿¤À¤ÎÊ¸»úÎó¤Ç¤¹¡£¤¿¤È¤¨¤Ð¤µ¤Ã¤­¤Îgcd¤À¤Ã¤¿¤é¡¢
¡Öl¡×¡Öe¡×¡Öt¡×¡Ö ¡×¡Ör¡×¡Öe¡×¡Öc¡×¡Ö ¡×¡Ög¡×¡Öc¡×¡Öd¡×¡Ö ¡×¡Öm¡×¡Ö ¡×¡Ön¡×¡Ö ¡×¡Ö=¡×...
¤Î¤è¤¦¤Ë¸«¤¨¤??±¤Ç¤¹¡£¤³¤Î¤Þ¤Þ¤Ç¤Ï²¿¤â¤Ç¤­¤Ê¤¤¤Î¤Ç¡¢¤Þ¤º
¡Ölet¡×¡Örec¡×¡Ögcd¡×¡Öm¡×¡Ön¡×¡Ö=¡×...
¤Î¤è¤¦¤Ê»ú¶ç¤Ë¶èÀÚ¤ê¤Þ¤¹¡£¤³¤Î½èÍ?ò»ú¶ç²òÀÏ¤È¤¤¤¤¤Þ¤¹¡£
 
»ú¶ç²òÀÏ¤Ë¤Ï¤¤¤úÀ¤¤úÀÊÊ?¡¤¬¤¢¤ê¤Þ¤¹¤¬¡¢¤³¤³¤Ç¤Ïocamllex¤È¤¤¤¦¡¢¤Þ¤µ¤ËOCaml¤Ç»ú¶ç²òÀÏ¤ò¤¹¤?¿¤á¤Î¥Ä¡¼¥?òÍøÍÑ¤·¤Þ¤¹¡£¤½¤Î¥Õ¥¡¥¤¥?¬lexer.mll¤Ç¤¹¡£ocamllex¤Ë¤Ä¤¤¤Æ¤Î¾ÜºÙ¤Ï¥Þ¥Ë¥å¥¢¥?Ê¤Ê¤¤¤·ÏÂÌõ¡Ë¤ò»²¾È¤·¤Æ¤â¤é¤¦¤³¤È¤Ë¤·¤Æ¡¢³µÍ×¤À¤±ÀâÌÀ¤¹¤?È¡¢
 
| '-'? digit+
    { INT(int_of_string (Lexing.lexeme lexbuf)) }
 
¤È¤¤¤Ã¤¿¥Ñ¥¿¡¼¥ó¥Þ¥Ã¥Á¥ó¥°¤Î¤è¤¦¤Ê¹½Ê¸¤Ë¤è¤ê¡¢¡ÖÀµµ¬É½¸½'-'? digit+¤Ë¥Þ¥Ã¥Á¤·¤¿¤é»ú¶çINT¤òÊÖ¤¹¡×Åù¤Î¥?¼¥?òÊÂ¤Ù¤Æ½ñ¤±¤ÐOK¤Ç¤¹¡£»ú¶ç¤òÉ½¤¹¥Ç¡¼¥¿·¿¡ÊINT¤Ê¤É¡Ë¤Ï¡¢¼¡¤Ë½Ò¤Ù¤?arser.mly¤ÇÄ?Á¤µ¤?Æ¤¤¤Þ¤¹¡£Lexing.lexeme lexbuf¤È¤¤¤¦ÉôÊ¬¤Ï¡¢²òÀÏÃæ¤ÎÊ¸»úÎó¤òÉ½¤¹¡Ö¤ª¤Þ¤¸¤Ê¤¤¡×¤À¤È»×¤Ã¤Æ¤¯¤À¤µ¤¤¡£
 
*/
package mincaml;
import java.io.*;
import mincaml.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/09/01 6:36 from the specification file
 * <tt>lexer.l</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\1\2\0\1\1\22\0\1\1\7\0\1\10\1\12"+
    "\1\11\1\24\1\35\1\25\1\22\1\26\12\2\1\0\1\41\1\30"+
    "\1\27\1\31\2\0\1\37\3\4\1\23\25\4\4\0\1\36\1\0"+
    "\1\16\1\3\1\34\1\3\1\6\1\15\1\3\1\33\1\32\2\3"+
    "\1\5\1\3\1\20\1\21\2\3\1\13\1\17\1\7\1\14\3\3"+
    "\1\40\1\3\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\4\4\1\5\1\1\1\6"+
    "\3\4\1\7\1\10\1\11\1\1\1\12\1\13\1\14"+
    "\1\4\1\15\1\16\1\1\1\17\1\0\1\20\4\4"+
    "\1\2\1\21\3\4\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\0\1\20\1\0\1\33"+
    "\3\4\1\34\1\4\1\35\1\0\1\36\1\37\1\40"+
    "\1\4\1\0\1\41\7\0\1\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\42\0\104\0\146\0\210\0\252\0\314\0\356"+
    "\0\u0110\0\u0132\0\42\0\u0154\0\u0176\0\u0198\0\42\0\u01ba"+
    "\0\u01dc\0\u01fe\0\42\0\u0220\0\u0242\0\u0264\0\42\0\42"+
    "\0\u0286\0\42\0\u02a8\0\u02ca\0\u02ec\0\u030e\0\u0330\0\u0352"+
    "\0\42\0\42\0\u0374\0\u0396\0\u03b8\0\42\0\42\0\42"+
    "\0\42\0\42\0\42\0\42\0\210\0\210\0\u03da\0\u03fc"+
    "\0\u03fc\0\210\0\u041e\0\u0440\0\u0462\0\210\0\u0484\0\210"+
    "\0\u04a6\0\210\0\210\0\210\0\u04c8\0\u04ea\0\210\0\u050c"+
    "\0\u052e\0\u0550\0\u0572\0\u0594\0\u05b6\0\u05d8\0\42";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\5\1\15\2\5\1\16"+
    "\1\5\1\17\1\2\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\2\5\1\27\1\30\1\31\1\5\1\32"+
    "\43\0\1\3\42\0\1\4\3\0\1\33\13\0\1\34"+
    "\1\33\20\0\6\5\3\0\7\5\1\0\1\5\6\0"+
    "\3\5\1\0\3\5\3\0\4\5\1\35\1\5\3\0"+
    "\7\5\1\0\1\5\6\0\3\5\1\0\3\5\3\0"+
    "\3\5\1\36\2\5\3\0\7\5\1\0\1\5\6\0"+
    "\3\5\1\0\3\5\3\0\6\5\3\0\1\37\6\5"+
    "\1\0\1\5\6\0\1\5\1\40\1\5\1\0\3\5"+
    "\12\0\1\41\52\0\1\42\21\0\4\5\1\43\1\5"+
    "\3\0\7\5\1\0\1\5\6\0\3\5\1\0\3\5"+
    "\3\0\6\5\3\0\3\5\1\44\3\5\1\0\1\5"+
    "\6\0\3\5\1\0\3\5\3\0\6\5\3\0\6\5"+
    "\1\45\1\0\1\5\6\0\3\5\1\0\3\5\23\0"+
    "\1\46\41\0\1\47\41\0\1\50\44\0\1\51\1\0"+
    "\1\52\1\0\1\53\37\0\1\54\14\0\6\5\3\0"+
    "\2\5\1\55\2\5\1\56\1\5\1\0\1\5\6\0"+
    "\3\5\1\0\3\5\14\0\1\57\30\0\1\60\21\0"+
    "\2\61\16\0\1\34\3\0\1\33\14\0\1\33\20\0"+
    "\5\5\1\62\3\0\7\5\1\0\1\5\6\0\3\5"+
    "\1\0\3\5\3\0\6\5\3\0\4\5\1\63\2\5"+
    "\1\0\1\5\6\0\3\5\1\0\3\5\3\0\6\5"+
    "\3\0\1\5\1\64\5\5\1\0\1\5\6\0\3\5"+
    "\1\0\3\5\3\0\4\5\1\65\1\5\3\0\7\5"+
    "\1\0\1\5\6\0\3\5\1\0\3\5\3\0\6\5"+
    "\3\0\7\5\1\0\1\5\6\0\2\5\1\66\1\0"+
    "\3\5\3\0\3\5\1\67\2\5\3\0\7\5\1\0"+
    "\1\5\6\0\3\5\1\0\3\5\3\0\5\5\1\70"+
    "\3\0\7\5\1\0\1\5\6\0\3\5\1\0\3\5"+
    "\14\0\1\71\30\0\1\60\41\0\4\5\1\72\1\5"+
    "\3\0\7\5\1\0\1\5\6\0\3\5\1\0\3\5"+
    "\3\0\4\5\1\73\1\5\3\0\7\5\1\0\1\5"+
    "\6\0\3\5\1\0\3\5\3\0\6\5\3\0\5\5"+
    "\1\74\1\5\1\0\1\5\6\0\3\5\1\0\3\5"+
    "\3\0\6\5\3\0\4\5\1\75\2\5\1\0\1\5"+
    "\6\0\3\5\1\0\3\5\17\0\1\76\25\0\4\5"+
    "\1\77\1\5\3\0\7\5\1\0\1\5\6\0\3\5"+
    "\1\0\3\5\41\0\1\100\23\0\1\101\53\0\1\102"+
    "\20\0\1\103\34\0\1\104\51\0\1\105\32\0\1\106"+
    "\40\0\1\107\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1530];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\1\11\3\1\1\11\3\1\1\11"+
    "\3\1\2\11\1\1\1\11\1\0\5\1\2\11\3\1"+
    "\7\11\2\1\1\0\1\1\1\0\7\1\1\0\4\1"+
    "\1\0\1\1\7\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }

  public static void main(String[] args) {
    try {
    Parser yyparser = new Parser(new FileReader(args[0]));
    while(true) {
      int rc = yyparser.yylex();
      System.out.println(rc);
      if (rc <= 0) break;
      if (rc == Parser.EOF) break;
    }
    } catch (Exception e){
      e.printStackTrace();
    }
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 106) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { return Parser.AST_DOT;
          }
        case 35: break;
        case 25: 
          { return Parser.IF;
          }
        case 36: break;
        case 8: 
          { return Parser.PLUS;
          }
        case 37: break;
        case 31: 
          { yyparser.yylval = new ParserVal(new Boolean(true)); return Parser.BOOL;
          }
        case 38: break;
        case 10: 
          { return Parser.EQUAL;
          }
        case 39: break;
        case 20: 
          { return Parser.SLASH_DOT;
          }
        case 40: break;
        case 34: 
          { return Parser.ARRAY_CREATE;
          }
        case 41: break;
        case 29: 
          { return Parser.NOT;
          }
        case 42: break;
        case 1: 
          { // token desconocido: se produce un mensaje de error 
          yyparser.yyerror("el(los) caracter(es) '"+yytext()+"' no forma(n) ningun token conocido");
          }
        case 43: break;
        case 4: 
          { yyparser.yylval = new ParserVal(""+yytext()); return Parser.IDENT;
          }
        case 44: break;
        case 23: 
          { return Parser.LESS_GREATER;
          }
        case 45: break;
        case 21: 
          { return Parser.LESS_MINUS;
          }
        case 46: break;
        case 13: 
          { return Parser.COMMA;
          }
        case 47: break;
        case 33: 
          { yyparser.yylval = new ParserVal(new Boolean(false)); return Parser.BOOL;
          }
        case 48: break;
        case 27: 
          { return Parser.LET;
          }
        case 49: break;
        case 24: 
          { return Parser.GREATER_EQUAL;
          }
        case 50: break;
        case 32: 
          { return Parser.THEN;
          }
        case 51: break;
        case 6: 
          { return Parser.RPAREN;
          }
        case 52: break;
        case 30: 
          { return Parser.ELSE;
          }
        case 53: break;
        case 11: 
          { return Parser.LESS;
          }
        case 54: break;
        case 28: 
          { return Parser.REC;
          }
        case 55: break;
        case 19: 
          { return Parser.MINUS_DOT;
          }
        case 56: break;
        case 14: 
          { yyparser.yylval = new ParserVal((Object)Id.gentmp(new Type.Unit())); return Parser.IDENT;
          }
        case 57: break;
        case 15: 
          { return Parser.SEMICOLON;
          }
        case 58: break;
        case 9: 
          { return Parser.MINUS;
          }
        case 59: break;
        case 7: 
          { return Parser.DOT;
          }
        case 60: break;
        case 5: 
          { return Parser.LPAREN;
          }
        case 61: break;
        case 26: 
          { return Parser.IN;
          }
        case 62: break;
        case 22: 
          { return Parser.LESS_EQUAL;
          }
        case 63: break;
        case 12: 
          { return Parser.GREATER;
          }
        case 64: break;
        case 18: 
          { return Parser.PLUS_DOT;
          }
        case 65: break;
        case 16: 
          { yyparser.yylval = new ParserVal(Double.parseDouble(yytext())); return Parser.FLOAT;
          }
        case 66: break;
        case 3: 
          { yyparser.yylval = new ParserVal(Integer.parseInt(yytext())); return Parser.INT;
          }
        case 67: break;
        case 2: 
          { 
          }
        case 68: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                /*return Parser.EOF;*/ return YYEOF;
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
